model_params:
  num_layers: 6
  d_model: 256
  dff: 1024
  num_heads: 8
  dropout_rate: 0.1
  max_posit_encode_input: 1000
  max_posit_encode_target: 1000

dataset_params:
  batch_size: 64
  translate_tokenizers_model: ted_hrlr_translate_pt_en_converter
  tf_dataset_name: 'ted_hrlr_translate/pt_to_en'

train_params:
  epochs: 200
  steps_per_epoch: 800
  validation_steps: 20
#  save_freq: 10

metric_params:
#  bleu:
#    max_order: 2
#  gleu:
